### ISSUE TITLE
grainID

### ISSUE THREAD

**Issue by Hubin-Luo** [pierrehirel/atomsk#1]
It seemed that the auxiliary properties did not work when I tried to visualize a constructed polycrystal in OVITO with color coding according to grain ID. All atoms in the simulation cell belong to one grain ID. I examined the CFG file. Only one line is found with the keyword "grainID": "auxiliary[0] = grainID", and the other lines are atomic positions. It seems that auxiliary[] is a list and there should be lines with auxiliary[1], auxiliary[2]..., I am not sure and do not know where they should be.

**Comment by pierrehirel** [comment]
Dear @Hubin-Luo ,
Thank you for your message.
Can you please provide the following information so that I can investigate this issue:

- your operating system (Linux, Windows, Mac)
- the version of Atomsk you are running
- the sequence of commands that you have run, and produced the issue
- the final CFG file that you obtained.

Without such information, I cannot address your issue.
Sincerly

**Comment by Hubin-Luo** [comment]
[final.zip](https://github.com/pierrehirel/atomsk/files/1615624/final.zip)
Dear Pierrehirel,

I tried both Linux compiled from the source code and also the binary version for Windows (run in powershell). The result is the same. The version is the newest ones (b0.9.10 and also the master version). 
I followed your instruction in the tutorial like: atomsk --polycrystal smco.xsf polycrystal.txt final.cfg -wrap.
where smco.xsf is the file of the unit cell. 

Attached please find the final.cfg.

Best


Hubin

**Comment by pierrehirel** [comment]
Dear @Hubin-Luo ,

I see nothing wrong in your final CFG file (except that the system is very small, so the grains contain only a few atoms).

The grainID is a single property (this is why there is only one auxiliary property defined in the final CFG file). This property takes different values depending on the atom. In your example, there are four grains, therefore some atoms have grainID=1, while others have grainID=2, 3 or 4.
To visualize this in Ovito, click Add modification, Color coding, then under Particle property select "grainID", and then click the button "Adjust range". You should see each grain with a different color.

Please tell me if this solves your problem.

Best regards

**Comment by Hubin-Luo** [comment]
Dear @pierrehirel ,

YES! It works. I am new to OVITO so this makes easy things look tricky. Thank you very much.

I do have a question for understanding. How can OVITO select the grainID property of atoms since in the CFG file there is only one line about grain ID while the other information seems to be nothing to do with the property?

Best regards
Hubin

**Comment by pierrehirel** [comment]
You are welcome.

In the CFG file format, by default each atoms is characterized by three real numbers, defining its position X, Y, Z. However you will notice that, in your file, each line contains four real numbers. The last one corresponds to an auxiliary property. What is the name of this auxiliary property? Well, it is defined in the line auxiliary[0], and of course it is the grainID. So, the fourth number can take a value of 1, 2, or 3 (for practical reasons it appears as 1.000E+01 and so on).

If another auxiliary property were defined for atoms (for instance, their binding energy), then you would have an additional line at the beginning of the file saying auxiliary[1]='binding energy', and you would have an additional real number at the end of each line.

So, when you open the CFG file with Ovito (or with Atomeye, or with any viewer that supports the CFG format), it knows that the numbers in the 4th column correspond to auxiliary[0], and it knows the name of that auxiliary property.

If you are to work with the CFG file format, I recommend that you get familiar with it by reading its specification: http://li.mit.edu/Archive/Graphics/A/#extended_CFG

With this I close this issue.

Best regards
