### ISSUE TITLE
how to change lattice parameter of the substituting material?

### ISSUE THREAD

**Issue by debopriyo-git** [pierrehirel/atomsk#18]
Hello Sir,
when creating a poly crystalline alloy ex- Ti-Al,where is am interested in changing the composition of the alloy, is it possible to change the lattice parameters of both Ti and Al, especially Al since Al is the substituting material?if yes then how I can change the lattice constant of Al?
please help.
regards,
Debopriyo Banerjee
NIT Durgapur

**Comment by pierrehirel** [comment]
Dear Sir,

I am not sure what you mean by "the lattice constant of substitutional Al". I agree that in a Ti lattice, if one Ti atom is replaced by an Al atom, then it will have different bond length, however it will not be equal to the lattice parameter of bulk Al.

Atomsk is not a tool to modify the bond lengths locally, or define a bond length for each atom. This requires knowledge of the local interactions between atoms. What I suggest is generating the Ti polycrystal, then substitute some atoms with Al, and run a DFT or molecular dynamics simulation with that system. Only the simulation integrating the correct physics can produce the correct bond length.

Best regards

**Comment by pierrehirel** [comment]
Without further answer for over a month I close this issue.

**Comment by debopriyo-git** [comment]
Respected sir,
Your address to the issue just allowed me to explore more options and
thanks to you, I found a way to approach the aforesaid issue that I raised.
Once again thanks for the help sir.much respect!!!
Debopriyo
