### ISSUE TITLE
How to select random atoms within a specific region

### ISSUE THREAD

**Issue by AIzquierdo2** [pierrehirel/atomsk#20]
Hi, 

I am wondering how to select atoms randomly but that match a certain criteria. For instance, suppose I have a supercell and I want to select say 18 random atoms but only within the upper half of the box.

When I use the "-select in box" option paired with the "-select intersect random 18 any", first the upper half is selected but the selection is replaced with 10 random atoms within the entire supercell. Maybe the syntax is incorrect. I used

atomsk initial.xyz -select in box 0 198 0 INF 372 INF -select intersect random 18 Fe -rmatom select final.xyz

I get the following messages

 ..> Input file was read successfully (365184 atoms).
 >>> Selecting atoms inside the box.
 ..> Box bounds: (0.000,198.000,0.000); (+INF,372.000,+INF).
 ..> 156950 atoms are now selected.
 >>> Selecting randomly 18 atoms of Fe.
 ..> 156942 atoms were removed from the selection.
 ..> 8 atoms are now selected.
 >>> Removing all selected atoms from the system.
 ..> 8 atoms were removed, 365176 atoms left.
 <i> Selected atoms were removed: the selection previously defined was cleared.
 >>> Writing output file(s) (365176 atoms):

So only 8 atoms were removed rather than 18. The 8 could be any number since is the random option being applied to the whole supercell, then if the.

Sorry for the lengthy explanation but I hope it shows clearly what the issue is. Thanks a lot

Angel

**Comment by pierrehirel** [comment]
Dear Sir,

Thank you for bringing this to my attention. What you are asking for is actually not implemented in Atomsk.

The command that you mention above does the following: atoms inside the box are selected (let's call them atoms of group A); then 18 random atoms are selected (group B); and then the intersection between the two groups is computed. In other words, the 18 random atoms are not picked among group A, they are chosen among all atoms, and only after that the intersection between the two groups is selected.

I will think of a way to implement what you ask, and come back here when it is done.

In the mean time, I suggest you to split the system in two parts: construct a block of perfect crystal; then construct a block containing the 18 random vacancies; and finally, stack them on top on each other (this can be done with mode "--merge"). That should produce the result you expect.

Best regards

**Comment by pierrehirel** [comment]
I implemented the possibility to select atoms among a previous selection, with the keyword "among". You can try it by replacing "intersect" with "among" in your command-line:

`atomsk initial.xyz -select in box 0 198 0 INF 372 INF -select among random 18 Fe -rmatom select final.xyz`

Please let me know if it behaves as expected and if it fixes your problem.

**Comment by AIzquierdo2** [comment]
Dear Pierre, 

Thank you very much for looking into this. I had gone around this problem initially by making a short bash script that makes vacancies by a small amount and rejects the output if they were not all within the desired region. Not very efficient, as you can imagine.

I tested the implementation you made and it works. The only small issue, though, is that it seems that the X and Y axis are swapped so doing 

`atomsk initial.xyz -select in box 0 50 0 INF 0 INF -select among random 18 Fe -rmatom select final.xyz`

will ensure that the 18 vacancies are within a region 0 to INF on the X direction and 0 to 50 angstroms on Y direction. The Z axis works fine.

Thanks a lot for you kind assistance, 

Angel

**Comment by pierrehirel** [comment]
Yes the behaviour you describe is expected, because the syntax to select inside a box is:

`-select in box xmin ymin zmin xmax ymax zmax`

So, in your command you specified xmin=0 and xmax=INF, and ymin=50 and ymax=0. Atomsk automatically sorts things out so that ymin<ymax, that's why you end up with ymin=0 and ymax=50.

I know that this logic is different from what you can find in other codes, for instance LAMMPS uses the following syntax in the "region" command:

`region 1 block xlo xhi ylo yhi zlo zhi`

However Atomsk uses a different syntax, as explained above. Please refer to the documentation for more information.

Hope this solves the issue.

**Comment by AIzquierdo2** [comment]
Yes it does. Thank you very much for the quick reply.

regards
