### ISSUE TITLE
Does atomsk consider the overlapping atoms at grain boudary?

### ISSUE THREAD

**Issue by YoshieraHuang** [pierrehirel/atomsk#22]
I want to use atomsk to construct a poly crystal. But i have a question here. Some atoms in one grain may be too close to some atoms in other grain at grain boundary. These overlapping atoms may cause  problems for quenching. Does atomsk consider this?

**Comment by pierrehirel** [comment]
Dear Sir,

Atomsk cuts atoms that are outside of each grain, so most of the time it should be ok to perform a minimization and atoms should relax properly. If atoms happen to overlap, this is not taken into account during construction of the polycrystal.

However you can use the option "-remove-doubles" to delete overlapping atoms, see documentation page:

[https://atomsk.univ-lille.fr/doc/en/option_rmd.html](https://atomsk.univ-lille.fr/doc/en/option_rmd.html)

Best regards
