### ISSUE TITLE
Molecule ID limited to < 10000 when adding shells

### ISSUE THREAD

**Issue by jarinfrench** [pierrehirel/atomsk#24]
I'm creating a large cylindrical grain boundary structure of CeO2 that will be simulated using the core-shell model in LAMMPS. Using Atomsk, I am able to create the unit cell, and duplicate it to the desired size without issues. However, when I try to add the shells, once the number of molecule IDs reaches 10000, the value for the Atom section changes to "*****" instead of the actual molecule ID. The Bonds section lists the ID without any issues however.

Commands issued:
`atomsk --create fluorite 5.408 Ce O lmp`
`mv CeO2.lmp CeO2_unit_cell.lmp`
`atomsk CeO2_unit_cell.lmp -dup 50 50 5 CeO2_core_50x50x5_100.lmp`

I then run a script that generates a cylindrical grain boundary, giving an output file of e.g. CeO2_core_50x50x5_45degree_rcut0.85_removed.dat.

`atomsk ${input} -add-shells all -properties core_shell_CeO2_properties.txt ${output}`
where `${input}` and `${output}` are the input file and desired output file names respectively.

Contents of core_shell_CeO2_properties.txt:
```
# Charges for CeO2 crystal
charge
Ce -0.6475 4.6475
O  4.5667 -6.5667
```

And the relevant output from the final atomsk command:
```
...
Atoms # full
...
    199996  99998    4   0.000000      167.704285000000     135.200000000000      17.576000000000
    199997  99999    2   0.000000      169.616301000000     137.112017000000      17.576000000000
    199998  99999    4   0.000000      169.616301000000     137.112017000000      17.576000000000
    199999  *****    2   0.000000      169.616301000000     133.287983000000      20.280000000000
    200000  *****    4   0.000000      169.616301000000     133.287983000000      20.280000000000
    200001  *****    2   0.000000      171.528318000000     135.200000000000      20.280000000000
...
Bonds
...
       99998           2      199995      199996 
       99999           2      199997      199998 
      100000           2      199999      200000 
      100001           2      200001      200002 
...
```
I've attached the resultant file from my own script as CeO2_file.gz

[CeO2_file.gz](https://github.com/pierrehirel/atomsk/files/5319477/CeO2_file.gz)

Is there a setting I missed that will allow me to output the correct molecule ID?

```
$ atomsk --version
 (C) P. Hirel 2010 - Version master
```

**Comment by pierrehirel** [comment]
Dear Sir,

Thank you for reporting what is indeed a bug in Atomsk. I just pushed a new update that should solve the issue.

Your example script also made me realize that there was another bug: the "types" written in the "Masses" section were not generated correctly (there was a line indicating "XX"). This should be fixed in the new version as well.

Please test the latest master version and tell me if there are still problems.

Best regards

**Comment by jarinfrench** [comment]
It looks like the original issue is fixed, however, in the Bonds section there is only one bond type assigned.

**Comment by pierrehirel** [comment]
Indeed that is another issue. I just committed a new version that should solve that as well.
Please report if it works as expected, thank you.

**Comment by jarinfrench** [comment]
That all looks correct, thank you!
