### ISSUE TITLE
dyld: Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib

### ISSUE THREAD

**Issue by nileshjchoudhary** [pierrehirel/atomsk#26]
Dear Pierre, 
Thanks for great software, 
I installed the atomsk in mac OS, 
it installed but showing error when we use the atomsk 
dyld: Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib
Kindly let me know the solution 

Best
Nilesh

**Comment by pierrehirel** [comment]
Dear Nilesh,

I compiled the macOS version using a virtual machine running macOS 10.13. If you are running a different version, it may explain why it is not working.

I propose two solutions:

1. Install the required libraries on your system ("libquadmath").

2. Download the source code and compile it on your machine. If you choose to do so, I recommend downloading the latest source code from GitHub. Instructions for compilation can be found in the tutorials and also in the documentation:

https://atomsk.univ-lille.fr/tutorial_install.php
https://atomsk.univ-lille.fr/doc/en/install.html

I hope this helps you run Atomsk on your machine.

Best regards

**Comment by nileshjchoudhary** [comment]
Yes it resolved now,
using mac port, first is installed all the prerequisite, then it worked
