### ISSUE TITLE
Polycrystal

### ISSUE THREAD

**Issue by Tengfei-ZHENG** [pierrehirel/atomsk#29]
I want to build a polycrystal model containing 4 grains with different orientations. For example, the first, second, and third grain is x-[001], the fourth grain is x-[111]. Can you tell me how the size of the box sets along x in the parameter file "polycrystal.txt" to match the periodicity?

**Comment by pierrehirel** [comment]
Dear Sir,

This space is meant for discussions about the code: how to use it, report bugs, etc.

What you ask is how to design an atomic system. This step is your responsibility, it is up to you to think about your design, system size, crystal orientation and so on, on paper. Only after that, can you consider using a software (Atomsk or other) to achieve what you want.

Atomsk is not magic. If you do not know what system you want to construct, it cannot help you.

Best regards
