### ISSUE TITLE
BUG: Make error caused by `3700e23`

### ISSUE THREAD

**Issue by mjclarke94** [pierrehirel/atomsk#31]
Building the latest release causes a compilation error due to a missing file:

```
gfortran -O2 -DOPENMP -fopenmp -fno-backslash -I../OBJ -J../OBJ -o ../OBJ/mode_merge.o  -c mode_merge.f90
gfortran -O2 -DOPENMP -fopenmp -fno-backslash -I../OBJ -J../OBJ -o ../OBJ/1ia_dlpoly_history.o  -c 1ia_dlpoly_history.f90
gfortran -O2 -DOPENMP -fopenmp -fno-backslash -I../OBJ -J../OBJ -o ../OBJ/1ia_qe_out.o  -c 1ia_qe_out.f90
make[1]: *** No rule to make target `1ia_vasp_outcar.o', needed by `modes'.  Stop.
```

I checked out the previous commit and compiled with no issues so it seems to be an issue with the latest change.

**Comment by pierrehirel** [comment]
Dear Sir,
Thank you for pointing this out.
Turns out I forgot to add a new source file in my last commit (note to self: never commit late Friday when you are in a rush!).
I added the file today, along with updated documentation, everything should run fine now.
Best regards

**Comment by mjclarke94** [comment]
Haha, always a risky move. Thanks for the quick fix!
