### ISSUE TITLE
Tag releases on Github

### ISSUE THREAD

**Issue by jan-janssen** [pierrehirel/atomsk#35]
I noticed that Version 0.11 is available on the website but the tagged versions on this repository end at version 0.10 https://github.com/pierrehirel/atomsk/tags . Is it possible to publish tags for the latest versions as well? This would be helpful to create the conda package https://github.com/conda-forge/atomsk-feedstock/pull/14

**Comment by pierrehirel** [comment]
Dear Sir,

I just added a tag for version 0.11. I hope this helps you in your project

Best regards

**Comment by jan-janssen** [comment]
Thanks a lot. I updated the conda package, now every time a new atomsk version is released on GitHub a new conda package is created automatically. 
https://github.com/conda-forge/atomsk-feedstock/pull/15
