### ISSUE TITLE
X!X ERROR: memory (RAM) is insufficient to perform this operation

### ISSUE THREAD

**Issue by superssy** [pierrehirel/atomsk#37]
Dear Pierre,

First of all, thanks for creating this software which helps me a lot. When I wanted to create a larger polycrystal, the error appeared:X!X ERROR: memory (RAM) is insufficient to perform this operation. I already know that it is related to the ALLOCATE in Fortran. But, my computer has 16 GB of RAM, more than the error shows. Is there any method to solve this problem or I should change to a better computer?

Looking forward to your reply.
Yours sincerely. 
Siyao

**Comment by pierrehirel** [comment]
Dear Sir,

This message appears when Atomsk tries to allocate more memory than there is on the computer. The "required memory" is just an indication and may not be accurate.

When constructing polycrystals, this problem can arise if the seed that you provide is very large (several 100,000 atoms or more). I recommend to use a seed as small as possible, like a unit cell of the material. It can also arise if the target polycrystal is too large or 

If you are running Atomsk under Windows, know that it is a 32-bits version, which limits the memory allocation to 4 GB. That corresponds to about 125 millions of atoms. In order to model larger systems you need to run a 64-bits version of Atomsk (either compile it on Windows, or use a Linux computer), which can handle up to 2 billions of atoms.

I cannot say more without looking at your input files. If the solutions above does not work, please provide your input file and the command that you run with Atomsk, and alos the operating system that you use (Windows or Linux).

Best regards

**Comment by superssy** [comment]
Thanks for your constructive suggestions! I created poly-crystalline in win 10 before. Now I turn to use the subsystem WSL in win 10. The problem has been solved with a version beta-0.10.6 of atomsk. However, when I use the version beta-0.11.1 to generate poly crystalline, the error "malloc(): corrupted top size" appeared. I hope this is useful for you.
Finally thanks for your careful reply. Attached are test files and error messages.
Yours sincerely
Siyao




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pierrehirel/atomsk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pierrehirel/atomsk] X!X ERROR: memory (RAM) is insufficient to perform this operation (#37)





 
Dear Sir,
 
This message appears when Atomsk tries to allocate more memory than there is on the computer. The "required memory" is just an indication and may not be accurate.
 
When constructing polycrystals, this problem can arise if the seed that you provide is very large (several 100,000 atoms or more). I recommend to use a seed as small as possible, like a unit cell of the material. It can also arise if the target polycrystal is too large or
 
If you are running Atomsk under Windows, know that it is a 32-bits version, which limits the memory allocation to 4 GB. That corresponds to about 125 millions of atoms. In order to model larger systems you need to run a 64-bits version of Atomsk (either compile it on Windows, or use a Linux computer), which can handle up to 2 billions of atoms.
 
I cannot say more without looking at your input files. If the solutions above does not work, please provide your input file and the command that you run with Atomsk, and alos the operating system that you use (Windows or Linux).
 
Best regards
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by superssy** [comment]
[poly.txt](https://github.com/pierrehirel/atomsk/files/7159743/poly.txt)
![error](https://user-images.githubusercontent.com/50542929/133215568-16d46e6b-c723-4d72-8173-4dfb017353ad.png)
[pure.log](https://github.com/pierrehirel/atomsk/files/7159791/pure.log)

**Comment by superssy** [comment]
> There is no file attached to your message.

Here

**Comment by superssy** [comment]
I have uploaded the files to github.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pierrehirel/atomsk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pierrehirel/atomsk] X!X ERROR: memory (RAM) is insufficient to perform this operation (#37)





 
There is no file attached to your message.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pierrehirel** [comment]
Thank you for the files, it helped me figuring out the problem.

As I suspected, your seed ("pure.log", which is not a log file but a LAMMPS data file) is too large along the Z axis. I suggest that you reduce it, for example with the option "-reduce-cell Z" of Atomsk:

`atomsk pure.log -reduce-cell unitcell.lmp`

You can then use this unit cell as a seed to generate your polycrystal. If you wish to duplicate the polycrystal along the Z axis, you can do so with the option "-duplicate".

As a rule of thumb: in mode "--polycrystal", make the seed as small as possible to avoid problems.

With that said, there was anyway a bug in the code that caused a segmentation fault. I fixed that bug and committed a new version on GitHub. If you wish, you can download it and compile it. If you do, I would appreciate if you can confirm that it solved your problem.

Best regards

**Comment by superssy** [comment]
Through my test, the bug in the latest version of atomsk has been fixed. Besides,&nbsp; using atomsk under Linux, I can already create a polycrystalline I want. Files with the "lmp" suffix can not be uploaded to github, so I change it to "log". Finally, as a graduate student who has used atomsk for two years,&nbsp;I am very grateful for your careful reply. Actually, we already have a paper citing atomsk:"Cyclic Plasticity of CoCrFeMnNi High-Entropy Alloy (HEA): A Molecular Dynamics Simulation" X. Du et al., Int. J. Applied Mech. 13 (2021) 2150006".&nbsp;
Best wishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pierrehirel/atomsk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pierrehirel/atomsk] X!X ERROR: memory (RAM) is insufficient to perform this operation (#37)





 
Thank you for the files, it helped me figuring out the problem.
 
As I suspected, your seed ("pure.log", which is not a log file but a LAMMPS data file) is too large along the Z axis. I suggest that you reduce it, for example with the option "-reduce-cell Z" of Atomsk:
 
atomsk pure.log -reduce-cell unitcell.lmp
 
You can then use this unit cell as a seed to generate your polycrystal. If you wish to duplicate the polycrystal along the Z axis, you can do so with the option "-duplicate".
 
As a rule of thumb: in mode "--polycrystal", make the seed as small as possible to avoid problems.
 
With that said, there was anyway a bug in the code that caused a segmentation fault. I fixed that bug and committed a new version on GitHub. If you wish, you can download it and compile it. If you do, I would appreciate if you can confirm that it solved your problem.
 
Best regards
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pierrehirel** [comment]
Good, thank you for your reply. If it fixes the problem then I close this issue.
