### ISSUE TITLE
Option: -disloc file filename nu seems to not work well

### ISSUE THREAD

**Issue by lfbu** [pierrehirel/atomsk#38]
Dear Pierre,
Thanks for your efforts in developing Atomsk. 
Recently, I  have trouble creating a complex dislocation loop. When I tried to use -disloc file option, it seems to not work as I hoped. As shown in the attached screenshot, the program can't recognize the third parameter -- Poisson ratio.
Looking forward to your reply!

Best regards

![Snipaste_2021-12-10_15-50-47](https://user-images.githubusercontent.com/77143497/145537838-f936ba96-fdec-493a-867f-ba209365443e.png)

**Comment by pierrehirel** [comment]
Dear Sir/Madam,

Thank you for reporting this bug. I just pushed a new version on GitHub that should fix it, please confirm.

Please note that this feature is currently in development and may not be fully functional, in particular when the Burgers vector has components out of the loop plane.

Best regards

**Comment by lfbu** [comment]
Dear Pierre,

Thank you for your so prompt reply! I have compiled the source code in my VirtualBox. I'm sorry to inform you that 
it doesn't work yet! Although it does display "successful", the system doesn't have any change in fact!

The dislocline.txt is:
_dislocation 0 2.556 0
_0.2*box 0.2*box 0.5*box
0.2*box 0.6*box 0.5*box
0.6*box 0.6*box 0.5*box
0.6*box 0.2*box 0.5*box__

And I find that it seems to not read the file at all. Whether the file is in the correct form or not, it will succeed every time.
In addition, I want to know if it is possible to insert a dislocation whose slip plane is corrugated.

![1](https://user-images.githubusercontent.com/77143497/145567716-5311deb2-fa0c-4c95-bd96-0ac285c7b436.png)

**Comment by pierrehirel** [comment]
This option does not support reduced coordinates, i.e. given with the keyword "BOX". Coordinates **must** be given as real numbers in angströms.

**Comment by lfbu** [comment]
I'm really appreciated your kind reminder! It has been fixed and I have got what I want.
Hope that Atomsk will get better in the future!
Thanks again!

Best regards
