### ISSUE TITLE
Makefile.local requires access to /etc folder

### ISSUE THREAD

**Issue by subhammridha** [pierrehirel/atomsk#4]
First of all thank you for this amazing tool.

I would like to know your views on a problem that I am facing while installing atomsk. I saw that there is a file `Makefile.local` in the `src` folder and wanted to use that to install atomsk to my home folder instead of having it installed system wide. But the problem is while writing all the files, it tries to write a `atomsk.conf` file to the `/etc` folder for which it has no access. 

Is there any way this file can be written to my home folder instead of being written to the system wide `/etc` folder. Though I can modify the `Makefile` to incorporate such a change, I am unsure as to whether such an action will enable the compiled `atomsk` binary to read the `atomsk.conf` file from my custom location.

I would prefer the compiled binary to read the configuration file from `~/.config/atomsk/atomsk.config` instead when installed locally!

Please help me sort this out.

**Comment by pierrehirel** [comment]
Hello,
Thank you for reporting this. I have modified the main Makefile as well as the Makefile.local in the master branch, you may test it now.
By default the configuration file ("atomsk.conf") is now placed in the user's home directory, in the folder .config. If you wish to place it elsewhere, just modify the Makefile.local.
Please tell me if this solves the issue.
Best regards

**Comment by subhammridha** [comment]
It took me some time to install it because I was issuing `make install` directly which, obviously, was throwing an error. Later I realised that I had to supply `make -f Makefile.local install` instead.

It seems to work now. Thanks again.
