### ISSUE TITLE
Issue: Undefined memory access

### ISSUE THREAD

**Issue by toor** [pierrehirel/atomsk#42]
I've discovered a strange bug when using Atomsk to generate a unit cell. The command I use is:
```bash
atomsk  --create  fcc 3.535 Fe orient [11-2] [1-10] [111]  -fractional  fcc_111_Fe.cfg
```
This immediately raises the error:
```
Program received signal SIGBUS: Access to an undefined portion of a memory object.
```
Hope some light can be shed on this. Cheers

**Comment by toor** [comment]
I should probably also mention that here atomsk is being called from a Python script using the `subprocess` module.

**Comment by pierrehirel** [comment]
Dear Sir,

I was about to answer that I could not reproduce the issue, either with version 0.11.2 or the current master version. Therefore this bug is not caused by Atomsk itself.

I am not sure what is causing this bug. Maybe it comes from OpenMP: did you properly define OpenMP environment variables in your Python script? Did you try running Atomsk with a single thread (add "-nthreads 1" to your command line)?

**Comment by toor** [comment]
Hi,

I've tried to run with just a single thread but that seems to give another error, namely:

```bash
atomsk  --create  fcc 3.535 Fe orient [11-2] [1-10] [111]  -fractional  fcc_111_Fe.cfg -nthreads 1
  ___________________________________________________
 |              ___________                          |
 |     o---o    A T O M S K                          |
 |    o---o|    Version b0.11.2                      |
 |    |   |o    (C) 2010 Pierre Hirel                |
 |    o---o     https://atomsk.univ-lille.fr         |
 |___________________________________________________|
realloc(): invalid old size

Program received signal SIGABRT: Process abort signal.
``` (the first line is the command passed to `subprocess`)
I haven't defined any OpenMP environment variables in my script since I haven't really got any need to; it's quite a simple script. I don't think this is an issue with Atomsk or `subprocess`, but rather using one with the other seems to break stuff.

**Comment by pierrehirel** [comment]
I see you are using version 0.11.2. Did you try with the latest master version available from GitHub?

**Comment by toor** [comment]
No I haven't, I'll have a go now.

**Comment by toor** [comment]
I'm still experiencing the same issue after compiling the master version.

**Comment by toor** [comment]
Hi Pierre. I've managed to resolve this issue. It had to do with the fact that there were extra spaces in my input to Atomsk. Thanks for your help.
