### ISSUE TITLE
Problem when using -properties.

### ISSUE THREAD

**Issue by wilsonnieto** [pierrehirel/atomsk#44]
Hi,

I have the following disp.txt to use with the option -properties:

#Atom displacements(in angströms)
   
  displacement functions
   
  uz = 3.3*atan2(x,y)/(2*pi)

The idea is to generate a helix from an annulus. So I center the annulus in the coordinate (0,0,0) which is a corner of the simulation box and then apply the -properties option. In the line x=0 there is an error that shows:

  X!X ERROR: division by zero.

The problem is that according to the definition of atan2 this should not be the case since when x=0, atan2 goes to +- pi/2. Is this a bug in the code?

Thanks for the help,

Wilson Nieto

**Comment by pierrehirel** [comment]
Dear Sir,

Thank you for reporting this bug. I have now fixed it and committed it to the master version of GitHub. You may download the latest version from GitHub and compile it. If you have time, I would appreciate if you could confirm the bug is indeed fixed.

Best regards

**Comment by wilsonnieto** [comment]
Yes it is fixed! Thank you for the quick solution.

Best
