### ISSUE TITLE
Maximum size of generation in polycrystal mode

### ISSUE THREAD

**Issue by roshan4325** [pierrehirel/atomsk#47]
Want to generate a polycrystalline system with 1 um x 1um x 1 um dimensions. With the HPC, can generate a quarter of the system- 0.25 um x 0.25 um x 0.25 um. 

Anything above, the system shows a segmentation error related to the memory. Would there be any way around it?

**Comment by pierrehirel** [comment]
The limit depends on the size of the seed. With a small seed (typically a unit cell of 2 or 4 atoms) it should be possible to generate polycrystals with tens of millions of atoms. If your seed is too large (several hundreds or thousands of atoms), then you will not be able to generate a large polycrystal.

**Comment by pierrehirel** [comment]
Without any answer for more than a month I close this issue.
