### ISSUE TITLE
How to determine the average grain size in atomsk?

### ISSUE THREAD

**Issue by shujing1111** [pierrehirel/atomsk#48]
Dear Dr. Pierre,

I used Atomsk to create a polycrystal with the box size of 200x200x200 (A) consisting of 120 grains. So, how can I determine the average grain size? Thank you very much for your time.

Shu

**Comment by shujing1111** [comment]
And can the difference in grain size be controlled? Thanks.

**Comment by pierrehirel** [comment]
Hello,

Atomsk writes the size of each grain in a separate file (*id-size.txt). You can use this information to compute the average grain size.

For your second question, the answer is no, there is no built-in function to control the average grain size or the size dispersion. If you are using a parameter like "random 120", then Atomsk will generate a truly random distribution. If you wish to control the grain size, you have to use the keyword "node", and place the nodes according to the distribution that you want.

Best regards

**Comment by shujing1111** [comment]
Thank you very much for your reply.

Shujing

**Comment by shujing1111** [comment]
Hi Dr. Pierre, 
Does Atomsk output the grain boundary angles in polycrystal for the random case?

Shu

**Comment by pierrehirel** [comment]
Hello,

When using "random", Atomsk writes a file named "*_param.txt" with the nodes positions and the random angles that were generated. You can use this information to determine the disorientation between grains.

Best regards
