### ISSUE TITLE
pw output read incorrectly 

### ISSUE THREAD

**Issue by jure91** [pierrehirel/atomsk#5]
Hello,
I would like to convert quantum espresso output (geometry optimization) to a series of cif files. I tried to use atomsk, but coordinates and cell parameters/vectors in the output are wrong. I tried the following lines:
`atomsk --one-in-all geo_opt.txt cif`
`atomsk --one-in-all geo_opt.txt cif -u angstrom angstrom`
`atomsk --one-in-all geo_opt.txt cif -u angstrom angstrom -rebox`

I opened quantum espresso output file using xcrysden and everything looks ok there.  Quantum espresso output: [geo_opt.txt](https://github.com/pierrehirel/atomsk/files/2610340/geo_opt.txt)

**Comment by pierrehirel** [comment]
Dear Sir,

What you describe seems to be a bug in Atomsk. Thank you for reporting it, I will look into it next week.

**Comment by pierrehirel** [comment]
This bug is now fixed in the Master branch. You may download it and compile it.

If you or someone else has the time, can you please test it and confirm that it fixes the bug?

I will try to provide a new version on the Web site by the end of the week.

**Comment by jure91** [comment]
I tested it and it seems to work now. Thank you!
