### ISSUE TITLE
Construct heterostructures based on CSL or Zur algorithms.

### ISSUE THREAD

**Issue by hongyi-zhao** [pierrehirel/atomsk#52]
Does atomsk support construct heterostructures based on [CSL](https://pubs.acs.org/doi/10.1021/acs.jpcc.6b01496) or [Zur](https://pymatgen.org/pymatgen.analysis.interfaces.html#module-pymatgen.analysis.interfaces.zsl) algorithms?

BTW, the [CSL](https://pubs.acs.org/doi/10.1021/acs.jpcc.6b01496) algorithm has been implemented in [hetbuilder](https://hetbuilder.readthedocs.io/en/latest/implementation.html#theoretical-background).

Regards,
Zhao

**Comment by pierrehirel** [comment]
Hello,

No these algorithms are not implemented in Atomsk.

If another code does what you need, then use that other code...

Regards
