### ISSUE TITLE
Construct different stack models for an interface by sampling cell of non-identical displacement (CNID).

### ISSUE THREAD

**Issue by hongyi-zhao** [pierrehirel/atomsk#53]
By using the cell of [cell of non-identical displacement (CNID)](https://github.com/nmdl-mizo/interface_master#interface-master) technique, we can construct more reasonable and fewer interface models, thus greatly reducing the work of subsequent calculations. See [here](https://doi.org/10.1016/j.cpc.2021.108260) for more detailed explanations on [cell of non-identical displacement (CNID)](https://github.com/nmdl-mizo/interface_master#interface-master).

I want to know if atomsk supports this feature, aka, constructing different stack models for an interface by sampling [cell of non-identical displacement (CNID)](https://github.com/nmdl-mizo/interface_master#interface-master), as done in [interface_master](https://github.com/nmdl-mizo/interface_master)?

Regards,
Zhao

**Comment by pierrehirel** [comment]
Hello,

No these algorithms are not implemented in Atomsk.

If another code does what you need, then use that other code...

Regards
