### ISSUE TITLE
Create the nanotube and nanoscroll given in the examples of cif2tube.

### ISSUE THREAD

**Issue by hongyi-zhao** [pierrehirel/atomsk#56]
The cif2tube [paper](https://www.sciencedirect.com/science/article/abs/pii/S1876107016303066) gives [the following two examples](https://ars.els-cdn.com/content/image/1-s2.0-S1876107016303066-mmc1.zip):

```shell
werner@X10DAi:~/Downloads/1-s2.0-S1876107016303066-mmc1$ ls Chrysotile_Nanoscroll.xyz Imogolite_Nanotube.xyz
Chrysotile_Nanoscroll.xyz  Imogolite_Nanotube.xyz
```

Can we reproduce the same structures with atomsk?

[1-s2.0-S1876107016303066-mmc1.zip](https://github.com/pierrehirel/atomsk/files/14906884/1-s2.0-S1876107016303066-mmc1.zip)

Regards,
Zhao

**Comment by pierrehirel** [comment]
Please stop opening one issue every day to ask if this or that is implemented.

Read the documentation : if it is implemented then it is in the doc. If it is not in the doc then it is not implemented.

And again, if another code can do what you want, then use that other code.
