### ISSUE TITLE
Cannot find the FUNCTION "FINDLOC"

### ISSUE THREAD

**Issue by iamusen** [pierrehirel/atomsk#57]
Hi, 
How can I find and compile the .mod file with the FUNCTION "FINDLOC"? That required by the sort.f90 (line 362).
Best,

**Comment by iamusen** [comment]
after update gfortran to ver 8.4.1,
Error message shows as follows:
sort.f90:362:35:

       NP = FINDLOC(idlist(:),i,DIM=1)
                                   1
Error: Keyword argument requires explicit interface for procedure ‘findloc’ at (1)

**Comment by pierrehirel** [comment]
Dear Sir,

As stated in the documentation, Atomsk now requires Gfortran 9 or greater :

https://atomsk.univ-lille.fr/doc/en/install.html

Updating your compiler to the latest version should fix all problems.

Best regards
