### ISSUE TITLE
Grain boundary creation tutorial fails

### ISSUE THREAD

**Issue by jarinfrench** [pierrehirel/atomsk#6]
Fresh install of Atomsk (master version) on Mac Sierra 10.12.6
I have tried to follow the grain boundary tutorial, but have been unable to create the boundary.  Attached is a screenshot of my terminal.  The file polyX.txt is exactly the same as the tutorial (I have tried with and without the degree symbols).  I have also attached the three output files: polycrystal.cfg, polycrystal.dat, and polycrystal_nodes.xsf.  Looking at the cfg file in Ovito shows a strange structure (also attached).  Is this an issue on my end?
![image](https://user-images.githubusercontent.com/17358062/58670796-90d92f00-82fd-11e9-9e6f-405e19f07efd.png)

[polycrystal_nodes.xsf.txt](https://github.com/pierrehirel/atomsk/files/3239044/polycrystal_nodes.xsf.txt)
[polycrystal.cfg.txt](https://github.com/pierrehirel/atomsk/files/3239045/polycrystal.cfg.txt)
[polycrystal.dat.txt](https://github.com/pierrehirel/atomsk/files/3239046/polycrystal.dat.txt)

![ovito_of_cfg_Al_file](https://user-images.githubusercontent.com/17358062/58671307-65efda80-82ff-11e9-868b-a681dd89e847.png)

**Comment by pierrehirel** [comment]
Dear jarinfrench,

Thank you for reporting what is indeed a bug in the code. Apparently it was due to a mistake from my part when introducing parallelization with OpenMP, my bad.

I just fixed th code, it should work now, update me if it doesn't.

Regards

**Comment by jarinfrench** [comment]
That has fixed it, thank you.
