### ISSUE TITLE
Occasional missing atoms from grain boundary structure

### ISSUE THREAD

**Issue by jarinfrench** [pierrehirel/atomsk#7]
Master branch, Mac Sierra 10.12.6

When creating a grain boundary using the fluorite crystal structure, occasionally atoms will not be written, creating unexpected vacancies.  This only seems to occur when reading the seed file from a separate directory other than the current one.

Given a file structure as follows:
`$HOME/atomsk/unit_cells/uo2_seed.lmp`
`$HOME/atomsk/gbs/gb.txt`

where uo2_seed.lmp is the file created by the command `atomsk --create fluorite 5.453 U O lammps` and gb.txt contains the following lines
```
box 60.9663934 60.9663934 5.453
node 0.5*box 0.25*box 0 0° 0° -26.56°
node 0.5*box 0.75*box 0 0° 0° 26.56°
```

then running the following command in `$HOME/atomsk/gbs/gb.txt`:
`for i in $(seq 1 10); do atomsk --polycrystal ../unit_cells/uo2_seed.lmp gb.txt uo2_gb_${i}.lmp; done`
creates several uo2_gb files which can show different U or O vacancies (images attached)
[uo2_gbs.tar.gz](https://github.com/pierrehirel/atomsk/files/3242753/uo2_gbs.tar.gz)

If the seed file is copied to the same directory, and the same for command run, nearly all the files contain all atoms (I had run this several times without any apparent vacancies, but on the last test on U atom was missing - images attached [uo2_gbs_same_dir.tar.gz](https://github.com/pierrehirel/atomsk/files/3242783/uo2_gbs_same_dir.tar.gz))

I have also attached the associated .lmp files

[lmp_files.tar.gz](https://github.com/pierrehirel/atomsk/files/3242790/lmp_files.tar.gz)

**Comment by pierrehirel** [comment]
Hello,

Thank you for reporting this. Apparently it was due to an error in a loop parallelized with OpenMP, where the same variable was updated by several threads, thus causing the random errors that you reported. This behavior did not occur when using a single thread (with the command-line option "-nthreads 1").

The bug should now be corrected, and your script should work fine even with multiple threads.

Regards

**Comment by jarinfrench** [comment]
I can confirm that the script works as expected now, thank you.
